In [1]:
import sys
import os

# Adjust the path to point to the folder containing functions_flowpic_hanan.py
module_path = r"C:\Users\חנן\Desktop\אריאל אונ'\שנה ג\זיהוי התקפות\FlowPic\shachar code\histograms"
if module_path not in sys.path:
    sys.path.append(module_path)

# from functions_flowpic_hanan import process_packet_data, process_packet_data_with_direction

In [2]:
import os
import numpy as np
import pandas as pd
from functions_flowpic_hanan import process_packet_data,process_packet_data_with_direction 
from tensorflow.keras import models, layers 
from sklearn.model_selection import train_test_split
import tensorflow as tf

## make dataset

In [3]:
# Example usage
chat_df = pd.read_csv('combined_chat_dataset.csv')
video_df = pd.read_csv('combined_video_dataset.csv')
voip_df = pd.read_csv('combined_voip_dataset.csv')
file_df = pd.read_csv('combined_file_dataset.csv')

In [ ]:
# chat_histograms = process_packet_data(chat_df, window_size=60)
# video_histograms = process_packet_data(video_df, window_size=60)
# voip_histograms = process_packet_data(voip_df, window_size=60)
# file_histograms = process_packet_data(file_df, window_size=60)

In [4]:
# Adding a direction dimention to the images, whtie packets client, dark gray are server
chat_histograms = process_packet_data_with_direction (chat_df, window_size=60)
video_histograms = process_packet_data_with_direction (video_df, window_size=60)
voip_histograms = process_packet_data_with_direction (voip_df, window_size=60)
file_histograms = process_packet_data_with_direction (file_df, window_size=60)


Starting packet data processing with direction:

Creating histograms with direction:

Processing window 1 of 83

Processing window 2 of 83

Processing window 3 of 83

Processing window 4 of 83

Processing window 5 of 83

Processing window 6 of 83

Processing window 7 of 83

Processing window 8 of 83

Processing window 9 of 83

Processing window 10 of 83

Processing window 11 of 83

Processing window 12 of 83

Processing window 13 of 83

Processing window 14 of 83

Processing window 15 of 83

Processing window 16 of 83

Processing window 17 of 83

Processing window 18 of 83

Processing window 19 of 83

Processing window 20 of 83

Processing window 21 of 83

Processing window 22 of 83

Processing window 23 of 83

Processing window 24 of 83

Processing window 25 of 83

Processing window 26 of 83

Processing window 27 of 83

Processing window 28 of 83

Processing window 29 of 83

Processing window 30 of 83

Processing window 31 of 83

Processing window 32 of 83

Processing window 33 of 83

In [5]:
voip_histograms

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0

In [6]:
# Convert each class's histograms to numpy arrays
chat_data = np.array(chat_histograms)
video_data = np.array(video_histograms)
voip_data = np.array(voip_histograms)
file_data = np.array(file_histograms)

In [7]:
# Create labels for each class (0: chat, 1: video, 2: voip, 3: file)
chat_labels = np.zeros(len(chat_histograms))
video_labels = np.ones(len(video_histograms))
voip_labels = np.full(len(voip_histograms), 2)
file_labels = np.full(len(file_histograms), 3)

In [8]:
chat_data.shape, video_data.shape, voip_data.shape, file_data.shape

((83, 1500, 1500), (146, 1500, 1500), (387, 1500, 1500), (86, 1500, 1500))

In [9]:
# Combine all data and labels
X = np.concatenate([chat_data, video_data, voip_data, file_data], axis=0)
y = np.concatenate([chat_labels, video_labels, voip_labels, file_labels])

In [14]:
# # Check if directory exists, if not create it
# directory = 'histograms'
# if not os.path.exists(directory):
#     os.makedirs(directory)
# # Save combined data and labels
# np.save('histograms/reg_X.npy', X)
# np.save('histograms/reg_y.npy', y)

In [10]:
# Check if directory exists, if not create it
directory = 'histograms'
if not os.path.exists(directory):
    os.makedirs(directory)
# Save combined data and labels
np.save('histograms/reg_X_direction.npy', X)
np.save('histograms/reg_y_direction.npy', y)

In [12]:
# Print shapes for verification
print(f"Final X shape: {X.shape}")
print(f"Final y shape: {y.shape}")
print(f"Number of samples per class: Chat={len(chat_data)}, Video={len(video_data)}, VoIP={len(voip_data)}, File={len(file_data)}")

Final X shape: (702, 1500, 1500)
Final y shape: (702,)
Number of samples per class: Chat=83, Video=146, VoIP=387, File=86


In [13]:
assert X.shape[0] == y.shape[0]

In [14]:
del chat_df, video_df, voip_df, file_df, chat_histograms, video_histograms, voip_histograms, file_histograms

In [15]:
del chat_data, video_data, voip_data, file_data

## load data and make model

In [17]:
# # Load the data
# X = np.load('histograms/reg_X.npy')
# y = np.load('histograms/reg_y.npy')

In [20]:
# Load the data
X = np.load('histograms/reg_X_direction.npy')
y = np.load('histograms/reg_y_direction.npy')

In [21]:
# Shuffle and split the data
# First split: 80% train+val, 20% test
X_trainval, X_test, y_trainval, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Second split: 75% train, 25% validation (from the remaining 80%)
X_train, X_val, y_train, y_val = train_test_split(X_trainval, y_trainval, test_size=0.25, random_state=42)

# Print shapes to verify
print(f'Training set shape: {X_train.shape} {y_train.shape}')

Training set shape: (420, 1500, 1500) (420,)


In [ ]:
# # save the data
# np.save('histograms/reg_X_train.npy', X_train)
# np.save('histograms/reg_X_val.npy', X_val)
# np.save('histograms/reg_X_test.npy', X_test)
# np.save('histograms/reg_y_train.npy', y_train)
# np.save('histograms/reg_y_val.npy', y_val)
# np.save('histograms/reg_y_test.npy', y_test)

In [22]:
# save the data
np.save('histograms/reg_X_direction_train.npy', X_train)
np.save('histograms/reg_X_direction_val.npy', X_val)
np.save('histograms/reg_X_direction_test.npy', X_test)
np.save('histograms/reg_y_direction_train.npy', y_train)
np.save('histograms/reg_y_direction_val.npy', y_val)
np.save('histograms/reg_y_direction_test.npy', y_test)

In [3]:
# Load the data
X_train = np.load('histograms/reg_X_train.npy')
X_val = np.load('histograms/reg_X_val.npy')
# X_test = np.load('histograms/reg_X_test.npy')
y_train = np.load('histograms/reg_y_train.npy')
y_val = np.load('histograms/reg_y_val.npy')
# y_test = np.load('histograms/reg_y_test.npy')

In [4]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((420, 1500, 1500), (141, 1500, 1500), (420,), (141,))

In [5]:
train_data = tf.data.Dataset.from_tensor_slices((X_train, y_train))
val_data = tf.data.Dataset.from_tensor_slices((X_val, y_val))

In [14]:
# Data shape: (420, 1500, 1500)
# INPUT_SHAPE = (1500, 1500, 1)  # Assuming grayscale images, if RGB use (1500, 1500, 3)
INPUT_SHAPE = (1500, 1500)

In [9]:
# Check if X_train and X_val are not None
if X_train is None or X_val is None:
    raise ValueError("X_train or X_val is None")

# Check if there are any NaN values in X_train and X_val
if np.isnan(X_train).any() or np.isnan(X_val).any():
    raise ValueError("X_train or X_val contains NaN values")

# Check the shapes of X_train and X_val
print(f"X_train shape: {X_train.shape}")
print(f"X_val shape: {X_val.shape}")

X_train shape: (420, 1500, 1500)
X_val shape: (141, 1500, 1500)


In [11]:
# Function to check dataset elements
def check_dataset(dataset, name):
    for i, (x, y) in enumerate(dataset):
        if x is None or y is None:
            raise ValueError(f"None value found in {name} at index {i}")
        
        # Check if x is a floating-point tensor before applying IsNan
        if x.dtype.is_floating:
            if tf.reduce_any(tf.math.is_nan(x)):
                raise ValueError(f"NaN value found in {name} at index {i} in features")
        
        # Check if y is a floating-point tensor before applying IsNan
        if y.dtype.is_floating:
            if tf.reduce_any(tf.math.is_nan(y)):
                raise ValueError(f"NaN value found in {name} at index {i} in labels")
        
        print(f"{name} element {i} - x shape: {x.shape}, y shape: {y.shape}")

# Assuming train_data and val_data are your TensorFlow datasets
check_dataset(train_data, "train_data")
check_dataset(val_data, "val_data")

train_data element 0 - x shape: (1500, 1500), y shape: ()
train_data element 1 - x shape: (1500, 1500), y shape: ()
train_data element 2 - x shape: (1500, 1500), y shape: ()
train_data element 3 - x shape: (1500, 1500), y shape: ()
train_data element 4 - x shape: (1500, 1500), y shape: ()
train_data element 5 - x shape: (1500, 1500), y shape: ()
train_data element 6 - x shape: (1500, 1500), y shape: ()
train_data element 7 - x shape: (1500, 1500), y shape: ()
train_data element 8 - x shape: (1500, 1500), y shape: ()
train_data element 9 - x shape: (1500, 1500), y shape: ()
train_data element 10 - x shape: (1500, 1500), y shape: ()
train_data element 11 - x shape: (1500, 1500), y shape: ()
train_data element 12 - x shape: (1500, 1500), y shape: ()
train_data element 13 - x shape: (1500, 1500), y shape: ()
train_data element 14 - x shape: (1500, 1500), y shape: ()
train_data element 15 - x shape: (1500, 1500), y shape: ()
train_data element 16 - x shape: (1500, 1500), y shape: ()
train_d

### first model try

In [15]:
model = models.Sequential()
model.add(layers.Flatten())
model.add(layers.Dense(4, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Step 3: Train the Model
# Assuming `train_dataset` and `val_dataset` are TensorFlow datasets created from your data
model.fit(X_train, epochs=10, validation_data= X_val)

MemoryError: Unable to allocate 3.52 GiB for an array with shape (420, 1500, 1500) and data type int32

In [22]:
# Step 1: Define the CNN Model
model = models.Sequential([
    # Convolutional Layer 1
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=INPUT_SHAPE),
    layers.MaxPooling2D((2, 2)),

    # Convolutional Layer 2
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Convolutional Layer 3
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Flatten the output
    layers.Flatten(),

    # Fully connected layer
    layers.Dense(128, activation='relu'),

    # Output layer (assuming 4 classes; adjust for your use case)
    layers.Dense(4, activation='softmax')  # Use 'sigmoid' for binary classification
])


C:\Users\shach\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
# Step 2: Compile the Model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',  # Use 'binary_crossentropy' for binary classification
              metrics=['accuracy'])


In [ ]:
# Step 3: Train the Model
# Assuming `train_dataset` and `val_dataset` are TensorFlow datasets created from your data
model.fit(X_train, epochs=10, validation_data= X_val)